
#version 450
uniform float iTime;
uniform vec3 iMouse;

layout(local_size_x = 16, local_size_y = 16) in;
layout(rgba8, binding = 2) uniform image2D outputImage;

layout(binding = 1) uniform FragUBO {
  mat4 invProjectionView;
  float near;
  float far;
}
camera;

void mainImage( out vec4 Color, in vec2 UV)
{
    // your code here
    Color = vec4(1);
    UV = UV - 0.5;
    UV = UV * 2;
    Color = vec4(UV.x,UV.y,0,1);
}

void main() {
  ivec2 pixelCoords = ivec2(gl_GlobalInvocationID.xy);
  ivec2 dims = imageSize(outputImage); // fetch image dimensions

  vec2 texCoord = vec2(float(pixelCoords.x) / float(dims.x),
                       float(pixelCoords.y) / float(dims.y));
  
  vec4 outColor;

  mainImage(outColor,texCoord);
  imageStore(outputImage, pixelCoords, outColor);
}




